FROM eclipse-temurin:17-jre-jammy

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY ./build/libs/*.jar app.jar

EXPOSE 919

ENTRYPOINT ["java", "-Xmx1024m", "-jar", "app.jar"]
