package com.msrp.backend.util

val SEARCH_CATEGORIES =
    listOf(
        "baseball",
        "basketball",
        "football",
        "soccer",
        "hockey",
        "golf",
        "tennis",
        "boxing",
        "wrestling",
        "cycling",
        "volleyball",
        "softball",
        "lacrosse",
        "rugby",
        "cricket",
        "archery",
        "bowling",
        "skateboarding",
        "snowboarding",
        "skiing",
        "surfing",
        "swimming",
        "running",
        "track and field",
        "gymnastics",
        "weightlifting",
        "martial arts",
        "badminton",
        "rowing",
        "climbing",
        "fencing",
        "polo",
        "equestrian",
        "motocross",
        "paintball",
        "airsoft",
        "billiards",
        "darts",
        "curling",
        "table tennis",
        "fishing",
        "hunting",
        "camping",
        "hiking",
        "kayaking",
        "canoeing",
        "scuba diving",
        "rock climbing",
        "birdwatching",
        "metal detecting",
        "guitar",
        "bass guitar",
        "electric guitar",
        "acoustic guitar",
        "drum kit",
        "trumpet",
        "saxophone",
        "violin",
        "piano keyboard",
        "synthesizer",
        "mandolin",
        "banjo",
        "ukulele",
        "harmonica",
        "accordion",
        "cello",
        "flute",
        "clarinet",
        "trombone",
        "tuba",
        "guitar amplifier",
        "trading cards",
        "pokemon cards",
        "magic the gathering",
        "comic books",
        "vinyl records",
        "coins",
        "stamps",
        "sports memorabilia",
        "autographs",
        "vintage posters",
        "vintage signs",
        "military memorabilia",
        "political memorabilia",
        "movie memorabilia",
        "hot wheels",
        "diecast cars",
        "action figures",
        "lego",
        "model trains",
        "video games",
        "retro video games",
        "nintendo",
        "playstation",
        "xbox",
        "sega",
        "atari",
        "vintage electronics",
        "vintage radio",
        "ham radio",
        "vintage television",
        "vintage computer",
        "turntable",
        "vintage stereo",
        "oscilloscope",
        "vintage typewriter",
        "vintage calculator",
        "film camera",
        "vintage camera",
        "camera lens",
        "darkroom equipment",
        "jewelry",
        "watches",
        "vintage watches",
        "pocket watch",
        "sterling silver",
        "vintage handbags",
        "sneakers",
        "vintage clothing",
        "vintage denim",
        "vintage band tee",
        "antique furniture",
        "vintage lamps",
        "vintage clocks",
        "vintage kitchenware",
        "vintage barware",
        "pottery",
        "vintage glassware",
        "vintage porcelain",
        "vintage cast iron",
        "vintage sewing machines",
        "vintage tools",
        "vintage locks",
        "board games",
        "pinball machines",
        "arcade machines",
        "jukeboxes",
        "remote control cars",
        "vintage toys",
        "vintage barbie",
        "oil paintings",
        "sculpture",
        "native american art",
        "taxidermy",
        "vintage maps",
        "telescopes",
        "microscopes",
        "scientific instruments",
        "golf clubs",
        "bicycles",
        "motorcycle parts",
        "reading books first edition",
        "vintage medical equipment",
        "super bowl",
        "world series",
        "nba finals",
        "stanley cup",
        "world cup soccer",
        "olympics",
        "nascar",
        "kentucky derby",
        "masters golf",
        "wimbledon",
        "us open tennis",
        "tour de france",
        "world wrestling entertainment",
        "boxing championship",
        "ufc",
        "college football championship",
        "march madness",
        "world series of poker",
        "coachella",
        "woodstock",
        "grateful dead",
        "rolling stones",
        "beatles",
        "elvis presley",
        "michael jackson",
        "concert tour",
        "grammy awards",
        "burning man",
        "oktoberfest",
        "mardi gras",
        "world expo",
        "world fair",
        "presidential inauguration",
        "space shuttle",
        "apollo moon landing",
        "world war ii",
        "civil war",
        "telescope",
        "astronomy",
        "astrophotography",
        "binoculars",
        "star atlas",
        "planetarium",
        "space memorabilia",
        "nasa",
        "cat",
        "dog",
        "aquarium",
        "reptile",
        "bird cage",
        "horse tack",
        "pet memorabilia",
        "taxidermy fish",
        "home brewing",
        "beer brewing",
        "wine making",
        "whiskey decanter",
        "vintage beer",
        "barware",
        "cocktail shaker",
        "vintage wine",
        "distilling equipment",
        "bicycle",
        "road bike",
        "mountain bike",
        "bmx bike",
        "vintage bicycle",
        "cycling equipment",
        "gardening",
        "bonsai",
        "vintage garden",
        "bird feeder",
        "insect collection",
        "fossil",
        "mineral specimen",
        "crystal",
        "meteorite",
        "cast iron cookware",
        "vintage kitchen",
        "copper cookware",
        "vintage cookbook",
        "espresso machine",
        "coffee grinder",
        "woodworking",
        "hand planes",
        "vintage drill press",
        "lathe",
        "vintage saw",
        "vintage sunglasses",
        "vintage belt",
        "vintage boots",
        "vintage scarf",
        "vintage wallet",
        "luxury handbag",
        "vintage luggage",
        "vintage globe",
        "vintage map",
        "travel memorabilia",
        "vintage compass",
        "first edition book",
        "vintage magazine",
        "signed book",
        "pulp fiction magazine",
        "vintage newspaper",
        "vintage puzzle",
        "chess set",
        "vintage card game",
        "tabletop rpg",
        "dungeons and dragons",
        "vintage car parts",
        "porsche parts",
        "mustang parts",
        "corvette parts",
        "vintage hood ornament",
        "gas station memorabilia",
        "vintage license plate",
        "vintage microscope",
        "vintage chemistry set",
        "vintage slide rule",
        "vintage anatomy",
        "vintage religious",
        "tibetan singing bowl",
        "vintage tarot",
        "native american pottery",
        "african art",
        "japanese woodblock print",
    )
