package com.msrp.backend.util

val SEARCH_CATEGORIES =
    listOf(
        "baseball",
        "basketball",
        "football",
        "soccer",
        "hockey",
        "golf",
        "tennis",
        "boxing",
        "wrestling",
        "cycling",
        "volleyball",
        "softball",
        "lacrosse",
        "rugby",
        "cricket",
        "archery",
        "bowling",
        "skateboarding",
        "snowboarding",
        "skiing",
        "surfing",
        "swimming",
        "running",
        "track and field",
        "gymnastics",
        "weightlifting",
        "martial arts",
        "badminton",
        "rowing",
        "climbing",
        "fencing",
        "polo",
        "equestrian",
        "motocross",
        "paintball",
        "airsoft",
        "billiards",
        "darts",
        "curling",
        "table tennis",
        "fishing",
        "hunting",
        "camping",
        "hiking",
        "kayaking",
        "canoeing",
        "scuba diving",
        "rock climbing",
        "birdwatching",
        "metal detecting",
        "guitar",
        "bass guitar",
        "electric guitar",
        "acoustic guitar",
        "drum kit",
        "trumpet",
        "saxophone",
        "violin",
        "piano keyboard",
        "synthesizer",
        "mandolin",
        "banjo",
        "ukulele",
        "harmonica",
        "accordion",
        "cello",
        "flute",
        "clarinet",
        "trombone",
        "tuba",
        "guitar amplifier",
        "trading cards",
        "pokemon cards",
        "magic the gathering",
        "comic books",
        "vinyl records",
        "coins",
        "stamps",
        "sports memorabilia",
        "autographs",
        "vintage posters",
        "vintage signs",
        "military memorabilia",
        "political memorabilia",
        "movie memorabilia",
        "hot wheels",
        "diecast cars",
        "action figures",
        "lego",
        "model trains",
        "video games",
        "retro video games",
        "nintendo",
        "playstation",
        "xbox",
        "sega",
        "atari",
        "vintage electronics",
        "vintage radio",
        "ham radio",
        "vintage television",
        "vintage computer",
        "turntable",
        "vintage stereo",
        "oscilloscope",
        "vintage typewriter",
        "vintage calculator",
        "film camera",
        "vintage camera",
        "camera lens",
        "darkroom equipment",
        "jewelry",
        "watches",
        "vintage watches",
        "pocket watch",
        "sterling silver",
        "vintage handbags",
        "sneakers",
        "vintage clothing",
        "vintage denim",
        "vintage band tee",
        "antique furniture",
        "vintage lamps",
        "vintage clocks",
        "vintage kitchenware",
        "vintage barware",
        "pottery",
        "vintage glassware",
        "vintage porcelain",
        "vintage cast iron",
        "vintage sewing machines",
        "vintage tools",
        "vintage locks",
        "board games",
        "pinball machines",
        "arcade machines",
        "jukeboxes",
        "remote control cars",
        "vintage toys",
        "vintage barbie",
        "oil paintings",
        "sculpture",
        "native american art",
        "taxidermy",
        "vintage maps",
        "telescopes",
        "microscopes",
        "scientific instruments",
        "golf clubs",
        "bicycles",
        "motorcycle parts",
        "reading books first edition",
        "vintage medical equipment",
        "super bowl",
        "world series",
        "nba finals",
        "stanley cup",
        "world cup soccer",
        "olympics",
        "nascar",
        "kentucky derby",
        "masters golf",
        "wimbledon",
        "us open tennis",
        "tour de france",
        "world wrestling entertainment",
        "boxing championship",
        "ufc",
        "college football championship",
        "march madness",
        "world series of poker",
        "coachella",
        "woodstock",
        "grateful dead",
        "rolling stones",
        "beatles",
        "elvis presley",
        "michael jackson",
        "concert tour",
        "grammy awards",
        "burning man",
        "oktoberfest",
        "mardi gras",
        "world expo",
        "world fair",
        "presidential inauguration",
        "space shuttle",
        "apollo moon landing",
        "world war ii",
        "civil war",
        "telescope",
        "astronomy",
        "astrophotography",
        "binoculars",
        "star atlas",
        "planetarium",
        "space memorabilia",
        "nasa",
        "cat",
        "dog",
        "aquarium",
        "reptile",
        "bird cage",
        "horse tack",
        "pet memorabilia",
        "taxidermy fish",
        "home brewing",
        "beer brewing",
        "wine making",
        "whiskey decanter",
        "vintage beer",
        "barware",
        "cocktail shaker",
        "vintage wine",
        "distilling equipment",
        "bicycle",
        "road bike",
        "mountain bike",
        "bmx bike",
        "vintage bicycle",
        "cycling equipment",
        "gardening",
        "bonsai",
        "vintage garden",
        "bird feeder",
        "insect collection",
        "fossil",
        "mineral specimen",
        "crystal",
        "meteorite",
        "cast iron cookware",
        "vintage kitchen",
        "copper cookware",
        "vintage cookbook",
        "espresso machine",
        "coffee grinder",
        "woodworking",
        "hand planes",
        "vintage drill press",
        "lathe",
        "vintage saw",
        "vintage sunglasses",
        "vintage belt",
        "vintage boots",
        "vintage scarf",
        "vintage wallet",
        "luxury handbag",
        "vintage luggage",
        "vintage globe",
        "vintage map",
        "travel memorabilia",
        "vintage compass",
        "first edition book",
        "vintage magazine",
        "signed book",
        "pulp fiction magazine",
        "vintage newspaper",
        "vintage puzzle",
        "chess set",
        "vintage card game",
        "tabletop rpg",
        "dungeons and dragons",
        "vintage car parts",
        "porsche parts",
        "mustang parts",
        "corvette parts",
        "vintage hood ornament",
        "gas station memorabilia",
        "vintage license plate",
        "vintage microscope",
        "vintage chemistry set",
        "vintage slide rule",
        "vintage anatomy",
        "vintage religious",
        "tibetan singing bowl",
        "vintage tarot",
        "native american pottery",
        "african art",
        "japanese woodblock print",
        "BMW parts",
        "Jeep parts",
        "Land Rover parts",
        "Volkswagen parts",
        "Subaru parts",
        "Ford truck parts",
        "vintage motorcycle",
        "vintage moped",
        "snowmobile",
        "ATV parts",
        "vintage race car memorabilia",
        "vintage hood ornament",
        "hammock",
        "camping stove",
        "camp lantern",
        "sleeping bag",
        "backpacking gear",
        "bushcraft",
        "survival gear",
        "dutch oven camping",
        "fire starter",
        "birding binoculars",
        "bird field guide",
        "ornithology",
        "wildlife photography",
        "spotting scope",
        "stained glass",
        "fused glass",
        "art glass",
        "mosaic tiles",
        "glass cutting tools",
        "leadlight panel",
        "stand mixer",
        "vintage blender",
        "waffle iron vintage",
        "vintage toaster",
        "vintage pressure cooker",
        "meat grinder",
        "ice cream maker",
        "soda siphon",
        "vintage kitchen scale",
        "vintage percolator",
        "quilting",
        "spinning wheel",
        "loom weaving",
        "cross stitch",
        "embroidery hoop",
        "lace bobbin",
        "knitting needles vintage",
        "sewing pattern vintage",
        "slot car racing",
        "model rockets",
        "balsa wood airplane",
        "vintage puppet",
        "mechanical bank",
        "tin wind-up toy",
        "antique doll",
        "dollhouse",
        "ventriloquist dummy",
        "magic trick set",
        "vintage marbles",
        "snow globe",
        "music box",
        "Hummel figurine",
        "Depression glass",
        "carnival glass",
        "milk glass",
        "Fiestaware",
        "Wedgwood",
        "Royal Doulton",
        "majolica pottery",
        "Toby jug",
        "art nouveau",
        "art deco",
        "Victorian antique",
        "daguerreotype",
        "tintype photograph",
        "nautical antique",
        "ship model",
        "sextant",
        "ship lantern",
        "diving helmet",
        "maritime chart",
        "scrimshaw",
        "vintage tin sign",
        "neon sign",
        "vintage gas pump",
        "vintage soda fountain equipment",
        "decoy duck carving",
        "weather vane",
        "butter mold",
        "stoneware crock",
        "redware pottery",
        "yellowware pottery",
        "vintage canning jar",
        "folk art",
        "outsider art",
        "hair art Victorian",
        "memento mori",
        "cabinet of curiosities",
        "entomology collection",
        "botanical illustration",
        "surveying instruments",
        "theodolite",
        "drafting tools",
        "letterpress printing",
        "bookbinding tools",
        "calligraphy set",
        "ceramics kiln",
        "pottery wheel",
        "glassblowing tools",
        "printmaking",
        "etching press",
        "lithography",
        "woodcarving",
        "leather tooling",
        "saddle making",
        "oil painting landscape",
        "watercolor painting",
        "vintage Christmas ornament",
        "Halloween collectible",
        "decorative plate",
        "vintage holiday decoration",
        "vintage candy mold",
        "vintage jello mold",
        "antique clock movement",
        "barometer antique",
        "aneroid barometer",
        "marine chronometer",
        "gimbal compass",
        "vintage sewing basket",
        "thimble collection",
        "button collection",
        "vintage ribbon spool",
        "typeface letterpress",
        "vintage seed packet",
        "vintage feed sack",
        "grain sack",
        "vintage quilt",
        "hooked rug",
        "braided rug vintage",
        "vintage tapestry",
        "needlepoint",
        "macrame",
        "vintage basket",
        "Native American basket",
        "sweetgrass basket",
        "vintage tin container",
        "advertising tin",
        "vintage tobacco tin",
        "vintage coffee tin",
        "vintage lunch box",
        "vintage thermos",
        "vintage canteen",
        "vintage mess kit",
        "WWII field gear",
        "vintage first aid kit",
        "vintage flashlight",
        "vintage camp cookware",
        "cast iron skillet",
        "vintage woodstove",
        "hand saw antique",
        "drawknife",
        "spokeshave",
        "hand brace drill",
        "drawplate wire",
        "farrier tools",
        "blacksmith anvil",
        "blacksmith tongs",
        "bellows antique",
        "cobbler tools",
        "shoemakers last",
        "vintage hatbox",
        "millinery supplies",
        "vintage hat form",
        "vintage gloves",
        "vintage parasol",
        "vintage fan",
        "vintage perfume bottle",
        "vintage compact",
        "vintage vanity set",
        "vintage shaving set",
        "straight razor",
        "barber pole",
        "vintage barbershop",
        "vintage optometry",
        "spectacles antique",
        "monocle",
        "lorgnette",
        "vintage hearing aid",
        "walking stick",
        "cane vintage",
        "vintage umbrella",
        "vintage ice skates",
        "vintage roller skates",
        "vintage sled",
        "vintage toboggan",
        "vintage tennis racket",
        "vintage badminton set",
        "vintage croquet set",
        "lawn bowling",
        "bocce ball",
        "horseshoe game",
        "ring toss game",
        "vintage dart board",
        "vintage poker set",
        "vintage mahjong set",
        "vintage Scrabble",
        "vintage Monopoly",
        "vintage jigsaw puzzle",
        "scented candles",
        "candle making supplies",
        "soy wax",
        "beeswax candles",
        "candle wicks",
        "wax melts",
        "essential oil diffuser",
        "reed diffuser",
        "incense burner",
        "incense sticks",
        "palo santo",
        "sage bundle",
        "himalayan salt lamp",
        "wireless charger",
        "power bank",
        "USB hub",
        "cable management",
        "LED strip lights",
        "smart plug",
        "smart bulb",
        "Raspberry Pi",
        "Arduino",
        "drone",
        "action camera",
        "dash cam",
        "baby monitor",
        "smart doorbell",
        "ring light",
        "webcam",
        "mechanical keyboard",
        "gaming mouse",
        "gaming headset",
        "cat tree",
        "cat toys",
        "cat treats",
        "cat bed",
        "cat carrier",
        "cat litter box",
        "cat scratching post",
        "cat collar",
        "cat harness",
        "dog bed",
        "dog crate",
        "dog harness",
        "dog toys",
        "dog treats",
        "dog leash",
        "dog collar",
        "dog coat",
        "dog stroller",
        "fish tank",
        "aquarium filter",
        "aquarium pump",
        "aquarium heater",
        "aquarium light",
        "aquarium decorations",
        "rabbit hutch",
        "hamster cage",
        "guinea pig supplies",
        "ferret cage",
        "turtle tank",
        "hermit crab",
        "reptile enclosure",
        "succulent plant",
        "cactus",
        "monstera plant",
        "pothos",
        "fiddle leaf fig",
        "snake plant",
        "air plant",
        "terrarium",
        "venus flytrap",
        "pitcher plant",
        "orchid",
        "peace lily",
        "lucky bamboo",
        "mushroom growing kit",
        "herb seeds",
        "wildflower seeds",
        "tomato seeds",
        "pepper seeds",
        "fruit tree",
        "lavender plant",
        "rose bush",
        "berry bush",
        "garden tools set",
        "garden hose",
        "garden sprinkler",
        "raised garden bed",
        "terracotta pot",
        "planter pot",
        "watering can",
        "pruning shears",
        "garden trowel",
        "garden fork",
        "wheelbarrow",
        "compost bin",
        "rain barrel",
        "trellis",
        "garden arbor",
        "bird bath",
        "garden statue",
        "wind chime",
        "solar garden light",
        "garden gnome",
        "dehumidifier",
        "humidifier",
        "air purifier",
        "HEPA filter",
        "space heater",
        "tower fan",
        "weighted blanket",
        "heated blanket",
        "blackout curtains",
        "area rug",
        "bath mat",
        "shower curtain",
        "shoe rack",
        "coat rack",
        "plant stand",
        "throw pillow",
        "storage ottoman",
        "desk lamp",
        "floor lamp",
        "ceiling fan",
        "door mat",
        "picture frame lot",
        "wall mirror",
        "standing desk",
        "monitor arm",
        "desk organizer",
        "label maker",
        "file cabinet",
        "instant pot",
        "air fryer",
        "sous vide",
        "food dehydrator",
        "bread maker",
        "yogurt maker",
        "pasta maker",
        "candy thermometer",
        "kitchen torch",
        "mortar and pestle",
        "spice grinder",
        "French press",
        "pour over coffee",
        "cold brew coffee maker",
        "kombucha kit",
        "sourdough starter",
        "bread proofing basket",
        "pizza stone",
        "baking steel",
        "cake decorating",
        "cookie cutter set",
        "silicone mold baking",
        "chocolate mold",
        "fondue set",
        "raclette grill",
        "hot pot electric",
        "tagine",
        "paella pan",
        "crepe pan",
        "tortilla press",
        "bamboo steamer",
        "wok carbon steel",
        "chef knife",
        "Japanese knife",
        "knife sharpener",
        "cutting board",
        "mandoline slicer",
        "picnic basket",
        "picnic blanket",
        "beach umbrella",
        "beach chair",
        "soft cooler",
        "outdoor grill",
        "pellet grill",
        "charcoal smoker",
        "outdoor pizza oven",
        "chiminea",
        "fire pit",
        "patio heater",
        "outdoor string lights",
        "camp table",
        "camp cot",
        "tarp",
        "headlamp",
        "water filter camping",
        "solar shower",
        "yoga mat",
        "foam roller",
        "resistance bands",
        "pull up bar",
        "kettlebell",
        "jump rope",
        "punching bag",
        "boxing gloves",
        "swim fins",
        "swim goggles",
        "wetsuit",
        "paddle board",
        "climbing harness",
        "climbing shoes",
        "carabiner",
        "belay device",
        "crash pad climbing",
        "massage gun",
        "acupressure mat",
        "heating pad",
        "TENS unit",
        "infrared sauna blanket",
        "jade roller",
        "gua sha tool",
        "face steamer",
        "LED face mask",
        "red light therapy",
        "white noise machine",
        "sleep mask",
        "sunrise alarm clock",
        "resin art",
        "epoxy resin",
        "alcohol ink art",
        "pour painting",
        "gouache paint",
        "alcohol markers",
        "brush pens",
        "rubber stamps",
        "cricut machine",
        "heat press",
        "tie dye kit",
        "washi tape",
        "scrapbooking",
        "card making",
        "leather journal",
        "button maker",
        "badge making",
        "origami paper",
        "resin mold",
        "sticker maker",
        "kalimba",
        "tongue drum",
        "handpan drum",
        "djembe drum",
        "cajon drum",
        "bongo drums",
        "steel drum",
        "didgeridoo",
        "theremin",
        "melodica",
        "tin whistle",
        "ocarina",
        "sitar",
        "guzheng",
        "bouzouki",
        "nyckelharpa",
        "hammered dulcimer",
        "autoharp",
        "lap steel guitar",
        "pedal steel guitar",
        "resonator guitar",
        "vintage windbreaker",
        "vintage tracksuit",
        "vintage varsity jacket",
        "vintage corduroy jacket",
        "vintage western shirt",
        "vintage Hawaiian shirt",
        "vintage workwear",
        "cowboy boots",
        "cowboy hat",
        "beret",
        "angle grinder",
        "band saw",
        "scroll saw",
        "router table",
        "jointer",
        "planer",
        "dovetail jig",
        "pipe clamps",
        "welding helmet",
        "plasma cutter",
        "metal lathe",
        "milling machine",
        "belt sander",
        "detail sander",
        "car subwoofer",
        "car amplifier",
        "seat covers",
        "floor mats",
        "jump starter",
        "tire inflator",
        "car jack",
        "impact wrench",
        "torque wrench",
        "socket set",
        "air compressor",
        "body filler",
        "spray gun auto",
        "DA polisher",
        "clay bar",
        "vinyl wrap",
        "roof rack",
        "trailer hitch",
        "winch",
        "rolling pin vintage",
        "cake stand",
        "pie dish",
        "springform pan",
        "bundt pan",
        "loaf pan set",
        "cast iron griddle",
        "basting brush",
        "meat thermometer",
        "immersion blender",
        "salad spinner",
        "colander",
        "mixing bowl set",
        "measuring cups vintage",
        "egg beater vintage",
        "apple peeler",
        "cherry pitter",
        "corn stripper",
        "melon baller",
        "oyster knife",
        "lobster crackers",
        "crawfish boil pot",
        "crab pot",
        "shrimp deveiner",
        "fish scaler",
        "fillet knife",
        "smoking chips",
        "grill brush",
        "grill grate",
        "chimney starter",
        "fire starters",
        "vegetable peeler",
        "box grater",
        "zester",
        "citrus juicer",
        "stand mixer attachments",
        "bread lame",
        "bench scraper",
        "offset spatula",
        "piping bag set",
        "candy mold",
        "ice cube tray novelty",
        "butter dish",
        "sugar dispenser",
        "salt cellar",
        "pepper mill",
        "oil cruet",
        "napkin rings",
        "placemats",
        "tablecloth",
        "bread box",
        "fruit bowl",
        "cookbook stand",
        "kitchen timer",
        "egg timer",
        "sand timer",
        "bird nest box",
        "bird seed",
        "squirrel feeder",
        "butterfly house",
        "mason bee house",
        "bat house",
        "garden kneeler",
        "knee pads gardening",
        "seed tray",
        "greenhouse",
        "cold frame",
        "grow light",
        "soil test kit",
        "pH meter",
        "moisture meter",
        "pruning saw",
        "grafting knife",
        "bulb planter",
        "soil blocker",
        "seed starting kit",
        "plant markers",
        "garden twine",
        "wire plant support",
        "tomato cage",
        "bean poles",
        "drip irrigation",
        "soaker hose",
        "hose reel",
        "sprinkler head",
        "spray nozzle",
        "pressure washer",
        "leaf rake",
        "lawn aerator",
        "grass seed",
        "fertilizer spreader",
        "weed puller",
        "hoe",
        "edger",
        "post hole digger",
        "pickaxe",
        "mattock",
        "dibber",
        "dibble stick",
        "cold brew jug",
        "tea infuser",
        "teapot cast iron",
        "gongfu tea set",
        "matcha whisk",
        "matcha bowl",
        "tea ceremony",
        "sake set",
        "shotoku glass",
        "ramen bowl",
        "sushi mat",
        "bento box",
        "rice cooker",
        "takoyaki pan",
        "okonomiyaki pan",
        "noodle strainer",
        "dumpling mold",
        "mooncake mold",
        "dim sum basket",
        "clay pot cookware",
        "churro maker",
        "waffle cone maker",
        "cotton candy machine",
        "popcorn machine",
        "snow cone machine",
        "shaved ice machine",
        "soft serve machine",
        "milkshake blender",
        "sandwich press",
        "panini press",
        "George Foreman grill",
        "countertop convection oven",
        "toaster oven",
        "electric skillet",
        "chafing dish",
        "warming tray",
        "buffet server",
        "ice bucket",
        "wine chiller",
        "wine rack",
        "decanter",
        "beer tap",
        "kegerator",
        "soda stream",
        "seltzer maker",
        "juicer",
        "wheatgrass juicer",
        "spiralizer",
        "food mill",
        "ricer",
        "tamis sieve",
        "chinois strainer",
        "spider skimmer",
        "wok ring",
        "wok burner",
        "propane burner",
        "turkey fryer",
        "crawfish boiler",
        "camp Dutch oven",
        "camp griddle",
        "mess kit camping",
        "freeze dried food",
        "MRE military",
    )
